logging:
    file:
        name: sboard.log
        path: /logs
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /


spring:
    servlet:
        multipart:
            location: uploads
            max-file-size: 10MB


    mail:
        host: smtp.gmail.com
        port: 587
        username: fafa5271783@gmail.com
        password: zjhq jyeu rxup ogyg
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    application:
        name: sboard
        version: ${version}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwerty123@
        url: jdbc:mysql://15.164.251.109:3306/board
        username: board
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates
